name: cicd

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

env:
  # docker.io as default registry (docker hub)
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Initialization

      # Checkout
      - uses: actions/checkout@v4
      # Using node
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.11

      # Build app

      # Install deps
      - name: Install dependencies
        run: npm ci
      # Lint
      - name: Start linting
        run: npm run lint
      # Building app
      - name: Build app
        run: npm run build

      # Docker

      # Login to dockerhub
      - name: Docker login
        if: github.event_name != 'pull_request'
        run: docker login -u ${{ secrets.DOCKERHUB_LOGIN }}
      # Build and push Docker image with Buildx (don't push on PR)
      - name: Build and push Docker image
        id: build-and-push
        run: |
          docker-compose build
          docker push "${{ env.IMAGE_NAME }}:latest"

  deploy:
    if: github.event_name != 'pull_request'
    needs: build
    name: Deploy to VPS
    runs-on: ubuntu-latest
    steps:
      - name: Connect to VPS by SSH, pull latest image and run container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            docker login -u ${{ secrets.DOCKERHUB_LOGIN }}
            docker pull "${{ env.IMAGE_NAME }}:latest"
            docker run --name lomguide -p 127.0.0.1:3000:8080/tcp -d "matimioioi/lom:latest"
